# Generated by Django 6.0.3 on 2026-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_studentclass_quiz_target_class_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='checked_by_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
